---
- hosts: local

  vars_files:
    - config/vars.yml

  tasks:
    - include: task/system.yml    tags=base
    - include: task/shell.yml     tags=base
    - include: task/vim.yml       tags=base
    # - include: task/asdf.yml      tags=base
    - include: task/overmind.yml  tags=applications
    - include: task/insomnia.yml  tags=applications