---
- hosts: local

  vars_files:
    - config/vars.yml

  tasks:
    - include: task/system.yml    tags=system
    - include: task/shell.yml     tags=shell
    - include: task/vim.yml       tags=vim
    - include: task/asdf.yml      tags=asdf