---
shell: "/usr/bin/zsh"
home:  "{{ ansible_env.HOME }}"
user:  "{{ ansible_env.USER }}"
download_dir: "{{ home }}/Downloads"
dotfiles_dir: "{{ playbook_dir }}/dotfiles"
local_binary_path: "/usr/local/bin"
