---
shell: "/usr/bin/zsh"
home:  "{{ ansible_env.HOME }}"
user:  "{{ ansible_env.USER }}"
download_dir: "{{ home }}/Downloads"
dotfiles_dir: "{{ playbook_dir }}/dotfiles"

# antigen
antigen_repo: https://github.com/zsh-users/antigen.git
antigen_dir: "{{ home }}/.antigen"

# base16
base16_shell_repo: https://github.com/chriskempson/base16-shell.git
base16_dest_dir: "{{ home }}/.base16/shell"

# vundle
vundle_repo: https://github.com/gmarik/Vundle.vim.git
vundle_path: "{{ home }}/.vim/bundle/Vundle.vim"

# asdf
ruby_plugin_repo: https://github.com/asdf-vm/asdf-ruby.git
node_plugin_repo: https://github.com/asdf-vm/asdf-nodejs.git
python_plugin_repo: https://github.com/tuvistavie/asdf-python.git
rust_plugin_repo: https://github.com/code-lever/asdf-rust.git
go_plugin_repo: https://github.com/kennyp/asdf-golang.git
erlang_plugin_repo: https://github.com/asdf-vm/asdf-erlang.git
elixir_plugin_repo: https://github.com/asdf-vm/asdf-elixir.git
clojure_plugin_repo: https://github.com/vic/asdf-clojure.git